# Generated by Django 5.0 on 2023-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="golink",
            name="hit_count",
            field=models.IntegerField(default=0),
        ),
    ]
